name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DOCS_REPO: Qitas/reader
      DOCS_DIR: reader
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.73.0'
          extended: true

      - name: Build Hugo
        run: HUGO_ENV=production hugo --gc --minify

      # - name: Deploy Hugo to gh-pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   env:
      #     ACTIONS_DEPLOY_KEY: ${{ secrets.QITAS_TOKEN }}
      #     PUBLISH_BRANCH: gh-pages
          # PUBLISH_DIR: ./public
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.QITAS_TOKEN }}
          external_repository: ${{ env.DOCS_REPO }}
          publish_dir: ./public
          commit_message: Sync Docs
